### ISSUE TITLE
Red wiggle in main.css

### ISSUE THREAD

**Issue by tashrifbillah** [tashrifbillah/vis-final-project#38]
Should it be
![image](https://user-images.githubusercontent.com/35086881/100969733-9373a080-3501-11eb-94fc-697b6b32e022.png)

this:

![image](https://user-images.githubusercontent.com/35086881/100969698-8191fd80-3501-11eb-8755-9bb8c7a2d1c8.png)

@natemortensen

**Comment by tashrifbillah** [comment]
Ping @natemortensen ?

**Comment by natemortensen** [comment]
Yep good catch! I am used to SCSS and it's hard to break my habits. Your fix is correct
