### ISSUE TITLE
[BUG] One div isn't closed, v-bind not found

### ISSUE THREAD

**Issue by tashrifbillah** [tashrifbillah/vis-final-project#44]
![image](https://user-images.githubusercontent.com/35086881/101225947-d435fb80-3660-11eb-9d09-0f612cb713c7.png)

How do we find whose container isn't closed?

@natemortensen @gordonwade

**Comment by tashrifbillah** [comment]
It's not in my line chart or map chart.

**Comment by tashrifbillah** [comment]
Found `<div class="all-content">` that was not closed.

**Comment by natemortensen** [comment]
Fixed

**Comment by tashrifbillah** [comment]
Hi @natemortensen , I meant `v-bind is not bound` issue for you. I had already fixed missing div before.

**Comment by tashrifbillah** [comment]
I pulled your commit and it looks like you fixed both the issues. I am going to undo my `<div>` insertion. Sorry about raising alarm.
