### ISSUE TITLE
[BUG] Radar chart tooltip texts not consistent across axes

### ISSUE THREAD

**Issue by tashrifbillah** [tashrifbillah/vis-final-project#53]
@gordonwade 

![image](https://user-images.githubusercontent.com/35086881/101290656-afad6100-37d1-11eb-854e-75a0a0b7e6f4.png)

However, other axes tip does not include the phrase like `in the WATER category`.

**Comment by gordonwade** [comment]
There are two separate behaviors. One when you hover over the park body (the inside area) and another when you hover over the circle (a specific point on the axis). So I think this is working as expected.

**Comment by tashrifbillah** [comment]
Okay, sorry about the false alarm. In both cases, are the activities the first three?
